const axios = require('axios');
const mongoose = require('mongoose');

async function runTest() {
  console.log('🧪 Starting Step 7 Manual Test (Predictive Wait Time)...');

  try {
    // Connect to DB just to grab the first waiting patient
    await mongoose.connect('mongodb://localhost:27018/clinicflow');
    const Patient = require('./models/Patient');
    const patient = await Patient.findOne({ status: 'waiting_general' });
    
    if (!patient) {
      console.log('❌ No waiting patients found in the database to test! Run the Step 5 test first to create one.');
      process.exit(1);
    }

    console.log(`🔍 Found Patient: ${patient.name} (Ticket: ${patient.ticketId})`);
    
    // Call the status endpoint like the React frontend does
    console.log(`🌐 Fetching real-time status from /api/queue/status/${patient.ticketId}...`);
    const res = await axios.get(`http://localhost:3001/api/queue/status/${patient.ticketId}`);
    
    const data = res.data.patient;
    
    console.log('\n🎉 SUCCESS! Queue Status Retrieved.');
    console.log(`- Patient Name: ${data.name}`);
    console.log(`- Queue Position: ${data.position}`);
    console.log(`- ✨ AI Wait Message Generated by Gemini:`);
    console.log(`    "${data.aiWaitMessage}"`);
    
  } catch (error) {
    console.error('❌ Test Failed:', error.response?.data || error.message);
  } finally {
    await mongoose.disconnect();
  }
}

runTest();
